### ISSUE TITLE
record speed

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#18]
loading a 1000 lines takes 20 seconds using teraterm vs 1 minute on console.

Also, there is a new special command added specifically for this. This commands lets you send the entire code instead of sending a single line.

**Comment by dudedigital** [comment]
Stream code may have been working but when I tried it, it did not. Maybe firmware changed. I had button use old method instead.

**Comment by gus-ghielec** [comment]
We can't even enter code

**Comment by taylorza** [comment]
@dudedigital what firmware do you have on the device?

I just tested the code with the latest firmware (v0.2.3) and the local copy of the `due-console` and the streaming works, this is commit hash 174675d6f0a0caaa4bba605bcd30c9c3e60f4d7a.

**Comment by dudedigital** [comment]
@taylorza I didn't think of it at the time until I commented earlier, but yes, my firmware is out of date.
