### ISSUE TITLE
button order

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#20]
record should be first and then play next

you have play stop record

change it to 

record play stop

and can we color the icons? green play, red record, blue stop?

**Comment by dudedigital** [comment]
I worked off the image you shared: 
![image](https://user-images.githubusercontent.com/8594271/235481809-fb0ac684-eed7-45cf-b8ca-46b4dc433dff.png)

**Comment by greg-norris** [comment]
We updated an image mockup on the Duelink website

https://duelink.com/software/console.html
