### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#25]
needs to be DUE icon

**Comment by greg-norris** [comment]
![DueIcon](https://user-images.githubusercontent.com/29868099/235461022-fbc11063-8d16-4fa3-a395-e5a2fa9f7357.png)

**Comment by gus-ghielec** [comment]
@greg-norris please add a ink to icon

**Comment by greg-norris** [comment]
https://github.com/ghi-electronics/duelink-website/blob/dev/images/favicon.ico
