### ISSUE TITLE
Add more code samples

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#34]
reply with samples @greg-norris

**Comment by greg-norris** [comment]
# BrainPad Pulse - LCD Bouncing ball
x=64 # Ball X location
y=32 # Ball Y location
r=5  # Ball radius
a=3  # Ball X Speed
b=2  # Ball Y Speed
@loop
   LCDClear(0)        # Clear the screen
   LCDCircle(1,x,y,r) # Draw the ball
   LCDShow()          # Update the screen

   x=x+a:y=y+b        # Move the ball
   
   # Check if the ball hit one of the edges
   #  if it did then reverse the direction and make a sound
   if x<r || x>=(128-r):a=-a:sound(500,16,100):end
   if y<r || y>=(64-r):b=-b:sound(2000,16,100):end
goto loop

**Comment by greg-norris** [comment]
### Hello World

```
# Print to output
Print("Hello World")
# Print to display, if available
# Will cause an error when using BrainPad Edge (SC007)
LcdClear(0)
LcdText("Hello World!",1, 30, 30)
LcdShow()
```
