### ISSUE TITLE
Name file  when saving

### ISSUE THREAD

**Issue by greg-norris** [ghi-electronics/due-console#43]
Since we've added load to the console, can we have a popup when saving the file to name it? I think this would be useful in a classroom setting in particular.

**Comment by dudedigital** [comment]
No, you cannot lol

**Comment by gus-ghielec** [comment]
We can't bring a pop up message that asks for the file name and then save? We certainly do something like that here https://makecode.brainpad.com

start new project, give it a name at the bottom and click save.
