### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#51]
We use # for comments in DUE. We need to select python as a language so comments are highlighted properly.

However, if there is a way to completely customize the highlighter, we need instructions so we can tweak it for DUE.

**Comment by dudedigital** [comment]
@gus-ghielec I spent awhile looking into this and most code highlighter rule files are tedious to write/understand. You can look at the following links for yourself to see the complexity for [CodeMirror](https://codemirror.net/examples/lang-package/) and the [Ace Editor](https://ace.c9.io/#nav=higlighter) (to name a few). Some even require you to run it through special compilers. 

The answer to this is a **very simple** custom editor that **only highlights your keywords**. I got something working with good potential, just needs a bit more polish.

**Comment by gus-ghielec** [comment]
Selecting python is good enough for now
