### ISSUE TITLE
firmware update

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#52]
The firmware update now asks the user for the type of connected device but this should be automatic.

@Palomino34 how do we detect what device it is in the loader mode? VID? or a command like version?

**Comment by gus-ghielec** [comment]
@dudedigital can we use 'n' to detect the device and automatically select the appropriate firmware (SC13 vs SC007)? The user can still select the version.

**Comment by dudedigital** [comment]
Auto select firmware and latest version complete.
