### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-console#53]
If the element support it, we should add +/- buttons to change the font size.

**Comment by dudedigital** [comment]
@gus-ghielec I will get to some of these next week. Extremely busy atm.

**Comment by dudedigital** [comment]
@gus-ghielec Since things are responsive, isn't `CTRL -` or `CTRL +` sufficient for zooming?

**Comment by gus-ghielec** [comment]
That is fine but perhaps we can mention this somewhere so users know

**Comment by gus-ghielec** [comment]
We want text size change inside the code element and not the browser raise of the entire page!! Reopening the issue.
