### ISSUE TITLE
Error Timeout

### ISSUE THREAD

**Issue by greg-norris** [ghi-electronics/due-console#54]
When running this code once, I get a Timeout if I make a change and try to record again. 

x=0
@loop
 print(x)
 x=x+1
 wait(1000)
goto loop

If I use println() instead of print() I don't get the timeout error when I make a change and try and re-record.  

x=0
@loop
 println(x)
 x=x+1
 wait(1000)
goto loop

Also notice the > appears in the Output window when I STOP the program. 

![image](https://github.com/ghi-electronics/due-console/assets/29868099/34f56997-9634-4fcc-9e3d-803482cb3818)

Then when I make a small change and hit record I see this:

![image](https://github.com/ghi-electronics/due-console/assets/29868099/442aa8be-6913-4616-8a8f-d9269fa50666)

If I reconnect the BrainPad Pulse and hit LIST the only thing that appears in the coding window is 

![image](https://github.com/ghi-electronics/due-console/assets/29868099/5f975b6c-5dd2-4e86-97f0-68b45b406b51)

**Comment by dudedigital** [comment]
We may need @taylorza to look into this issue. This is outside my expertise. Is the timeout coming from the browser's web serial implementation or the Brainpad? It has to do with `pgmstream` not succeeding a 2nd time. Same code works the first time, but fails the 2nd time after the code is modified.

```
wrote pgmstream()
write is sleeping
write is reading until &
Reading... Done? false
-> &
queued: &
Reading... Done? false
-> !
Reading... Done? false
!error timeout
-> 
-> >
queued: !error timeout
queued: >
Error: !error timeout
read until found (2) ['&', '!error timeout']
```
