### ISSUE TITLE
Log Window on Console

### ISSUE THREAD

**Issue by greg-norris** [ghi-electronics/due-console#57]
We changed Print() to Log(),  we need to find another name for the LOG window, since Log() now prints to the Output window.

**Comment by gus-ghielec** [comment]
Change to Trace

**Comment by dudedigital** [comment]
Output/Trace is confusing IMO. I'm calling it the following so it makes sense from the codebase to the frontend.

Print Output
Log Output

Can you guess which code command outputs to each?

**Comment by dudedigital** [comment]
Currently, print is everything returned while reading. How do we distinguish between print/log output from the board?

**Comment by gus-ghielec** [comment]
Print only "prints" to the screen and only screen. You are using an old firmware.

**Comment by gus-ghielec** [comment]
Log
Command Output

or

Log Output
Command Output

**Comment by dudedigital** [comment]
When I originally added Log, it was more of a history of actions. I updated it to be History now (actions with time prefixes) and changed Output to Log.
